# Generated by Django 3.2.6 on 2021-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcore', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
