# Generated by Django 3.2.6 on 2021-10-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcore', '0003_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
